---
title: "R Notebook"
output: html_notebook
---

```{r}
suppressPackageStartupMessages({
library(tidyverse)
library(lubridate)
library(modelr)
library(broom)
library(lmtest)
library(sandwich)
library(viridis)
library(PxWebApiData)
})
knitr::opts_chunk$set(echo=FALSE, include = FALSE)


```

```{r}
# vector med relevante kommunenummer
load("knr.Rdata")
```

```{r}
pm2_rW <- ApiData(
  urlTodata = "06035",
  Region = knr,
  ContentsCode = "KvPris",
  Boligtype = "01",
  Tid = c(as.character(2002:2017))
)

```

### Modell

```{r}
mod1 <- 'pm2 ~ aar_f + Total_ya_p + inc_k1 + inc_k5 + uni_k_mf + uni_l_mf + Trade_pc_100K'
```

### Dummy fylke og år

```{r}
pm2 %>% filter(fnr %in% c("11")) %>%
ggplot(mapping = aes(x = aar_d, y = res_m2)) +
scale_color_viridis(discrete = TRUE, option = "D") +
geom_line(aes(group = knavn, colour = knavn, size =knavn)) +
scale_size_manual(values = c(seq(2.0, 0.5, by = -0.1))) +
geom_hline(yintercept = 0) +
theme(legend.position = 'bottom')

```

### Modell for hvert år

```{r}
pm2_n$data[[1]] %>%
head(n = 5)

```
